### ISSUE TITLE
Not seeing RGB24 type

### ISSUE THREAD

**Issue by falldeaf** [andrew-raphael-lukasik/RawTextureDataProcessingExamples#2]
On Unity 2019.1.0f2 I'm getting the following error (for every instance of \<RGB24\>) when I include this code:
Assets\Editor\GaussianBlurRGB24Job.cs(31,29): error CS0246: The type or namespace name 'RGB24' could not be found (are you missing a using directive or an assembly reference?)

Is this a data type only included in a newer version of Unity?  The burst compiler package was available for this version but I can't find anything on the net for \<RGB24\>

**Comment by andrew-raphael-lukasik** [comment]
Make sure to include this file (|directory) in your project: [RawTextureDataProcessingExamples/Structures/RGB24.cs](https://github.com/andrew-raphael-lukasik/RawTextureDataProcessingExamples/blob/master/Structures/RGB24.cs)
